### ISSUE TITLE
Failed to Download Firmware Inormations

### ISSUE THREAD

**Issue by bpopp** [MegaPirateNG/FlashTool#22]
When trying to run the flashtool, I get the error, "Failed to Download Firmware Informations". Occasionally it will start to download, but never gets past 1%. I looked through the code, and it's apparently trying to pull down the XML file from "http://fw.megapirateng.com:8888/update.xml" which seems to be offline.

**Comment by SirAlex** [comment]
Hi, thanks for report, please try again. Build server was down for some
reason.
13 янв. 2015 г. 4:42 пользователь "Brian Popp" <notifications@github.com>
написал:

**Comment by bpopp** [comment]
Yep, that did it. Thanks!

**Comment by eltesco1** [comment]
Hi sir Alex I am having this same issue again, also cannot browse to megapirateng.com seems site may be Down?

**Comment by SirAlex** [comment]
Sorry, but server is down due out of money to pay for colocation service at DataCenter.

**Comment by eltesco1** [comment]
Hi Sir Alex

I am getting this error on compile:
 avr-gcc error:unrecognized command line option'assembler-with-cpp

*But I cannot find instructions to resolve, I think they are on the
megapirate forum which is Down?*

*Do you know how to resolve?*

*Thanks for your help*

**Comment by AlaskaJ** [comment]
Thanks SirAlex for all your work. For a non-techie your flashtool is a lifesaver cause I can't compile a sketch to save the life of me. Is there any way to have the flashtool work without going to the server by instead using firmware locally and the user just go to the site to update them?

**Comment by etechnox** [comment]
Now the megapirateng.com had close , is there anywhere I ccanget the documents and firmwares? The flash tools I downloaded can't work as it try to access the site.

**Comment by smurfy** [comment]
i could host another build server if its required and still used.

**Comment by SirAlex** [comment]
Build server still running, but domain name was not prolonged.

**Comment by smurfy** [comment]
can you provide an alternate domain? i

**Comment by etechnox** [comment]
I just bought another new crius aiop , just know that the website already close ... I can't really find the method to install the firmware from internet , maybe the megapirateng documentation is still useful, hope the domain still exist

**Comment by smurfy** [comment]
the docs are served by github with a cname to docs.megapirate....
I will remove that and edit this post with the "new" link.

**Comment by etechnox** [comment]
Can I download the firmware also , the flashtool can't use right? I had
mistakenly update with mission planner on the attempting process

**Comment by smurfy** [comment]
Currently the flashtool is unusable, because it can't reach the build server.
But you can build it yourself as described in the docs.

**Comment by etechnox** [comment]
I tried the who night , this error keep come out
avr-gcc: error: unrecognized command line option '-assembler-with-cpp'

**Comment by danil2009** [comment]
Hi Sir Alex
I want to back My quadcopter firmware using MegapirateNg 3, using flashtools. But now i cannot use flashtools. I hope you can fix the server.
thanks
Dida

**Comment by SirAlex** [comment]
@smurfy 
>can you provide an alternate domain?

Please, try to use **mpng.siralex.info** instead of **fw.megapirateng.com**

**Comment by smurfy** [comment]
@SirAlex will do another release soon. you need to change the url in the http://mpng.siralex.info:8888/update.xml as-well

**Comment by SirAlex** [comment]
@smurfy 
>http://mpng.siralex.info:8888/update.xml as-well

Done. :)

**Comment by meggerja** [comment]
Hello, can you tell me is there any normal way to use this flash tool ? I am not a IT gay like you and I have no idea how to make this working.  Thanks

**Comment by dzmitryDubrovin** [comment]
@meggerja 

For Windows:
at start menu type "Notepad" -> MouseRightClick at "notepad" menu item and select "Run as Administrator"
then at Notepad go to File -> Open, at opened window go to C:\Windows\System32\drivers\etc and open file "hosts" 
(**NOTE** that Notepad basicaly tries to open *.txt files and "hosts" doesn't have txt ext, so select "All files" at right corner dropdown)

add following at NEW LINE at end of file  
212.98.191.17 fw.megapirateng.com

save it and rerun FlashTool

**Comment by smurfy** [comment]
I will release a new version soon. @dzmitryDubrovin  solution should work too.

**Comment by meggerja** [comment]
Thank you ,  that's working :)

**Comment by smurfy** [comment]
Also i have just released a new build: https://github.com/MegaPirateNG/FlashTool/releases

@SirAlex please also change the current version in the update.xml to 1.1r3

**Comment by SirAlex** [comment]
@smurfy 
Done, thanks for new version :)
