### ISSUE TITLE
Fix port number for update.xml

### ISSUE THREAD

**Issue by ungerik** [MegaPirateNG/FlashTool#23]
This URL does not work:
FLASHTOOL_PATH_URI = http://fw.megapirateng.com:8888/update.xml

This works:
FLASHTOOL_PATH_URI = http://fw.megapirateng.com/update.xml

**Comment by smurfy** [comment]
@SirAlex should i create a new release or what did change?

**Comment by SirAlex** [comment]
Hi!
Looks like server was restarted and app.js doesn't started automatically. Now it's works fine, no need to change port.
