### ISSUE TITLE
Make flashtool work locally and user download firmware updates manually please

### ISSUE THREAD

**Issue by AlaskaJ** [MegaPirateNG/FlashTool#24]
Thanks SirAlex for all your work. For a non-techie your flashtool is a lifesaver cause I can't compile a sketch to save the life of me. Is there any way to have the flashtool work without going to the server by instead using firmware locally and the user just go to the site to update them?

**Comment by smurfy** [comment]
currently the Firmware is getting build on the server, based on the configuration the user specifies. 

i will have a look in what would be needed to make it possible to add a local build  option.

**Comment by AlaskaJ** [comment]
Thanks guys for all your work!
