### ISSUE TITLE
Server Not Found

### ISSUE THREAD

**Issue by hunterway55** [MegaPirateNG/FlashTool#25]
Hey, When flash tool trys to update software it reply's with failed to download firmware information. I tried hitting the url and its down. http://fw.megapirateng.com/update.xml http://fw.megapirateng.com:8888/update.xml. Is their a fix for this? Or an expect time that the server will be back up?

**Comment by ATi7** [comment]
Flash tool work  at this date ? I can use it ! ...what are the steps to configure and use it I understand that the server does not work....

**Comment by smurfy** [comment]
It works but without server its tricky. Ive updated the project for easier local usage.

**Comment by ATi7** [comment]
Thank you to respond me friend very happy ....
Could you explain me  in an easy way how to do it or could you tell me the steps?

**Comment by smurfy** [comment]
take a look at the https://github.com/MegaPirateNG/FlashTool/blob/master/README.md

**Comment by ATi7** [comment]
If I had already read that ... I am not really a programmer, but I try ,I see QT  consumes memory in my PC ... but I am going to try to see where I arrive.....

**Comment by ATi7** [comment]
smurfy ...please I finish download the Qt 5.1 ...

what is the next step or or what do I have to do ..considering that I'm not a programmer...
But I would appreciate if you could guide me...

**Comment by ATi7** [comment]
you can enumerate the steps with a  explanation ?

**Comment by ATi7** [comment]
Please where update the proyect to local used ?

**Comment by SirAlex** [comment]
@ATi7 
Please, try again to use FlashTool, server now works fine.

**Comment by ATi7** [comment]
Thank you very much ... I want to thank smurfy and Sr Alex for their help and for their explanations ... thank you for your excellent work and make it possible for us to use your information to be able to do our projects ... very happy for me and  God bless you and all ...

**Comment by ATi7** [comment]
Thank you smurfy and Sr Alex ..OK fine ... Sr Alex ....Is possible you have the motor map and the receiver  connection from  hexa frame  in crius aio pro v2 from megapirate ng 3.01r4 and 3.01.5r2 software ? I try see in the git hub  but the link not work

**Comment by ATi7** [comment]
Only I need the motor maps from 3.01r4 and 3.01.5r2 ....the motor maps link in the code not work ...Do you have available this ? please ...

**Comment by ATi7** [comment]
Only I need the motor maps hexa frame from 3.01r4 and 3.01.5r2 ....the motor maps link in the code not work ...Do you have available this ? please ...

**Comment by ATi7** [comment]
I can not  see the motor map from code 3.01r4 to hexa frame  .....Can I get it ? only I need this to finish my proyect ...

**Comment by ATi7** [comment]
Thank you

**Comment by ATi7** [comment]
Hello A Greeting forl all .......I report today the megapirate ng  flash tool not work ....please you can help me ? 
I would like to report a problem that I used the  3.01r4 code and that is that when all  is turned off on in a crius aio pro   ...this  activated and starts the motors sometime ...First I calibrate all motor and I used esc simonk in 1060 to 1860 calibration in my radio and the radio is futaba 9c ....
my question is would it be some program error or my error ....You can help me .....
